// Code generated by wrappers/go/internal/gen from /Users/axel/contrib/zxing-cpp.git/core/src/BarcodeFormat.h; DO NOT EDIT.

package zxingcpp

//go:generate go run ../internal/gen

// BarcodeFormat identifies a barcode format/symbology or a filter/group (e.g. AllReadable).
//
// Values are kept in sync with core/src/BarcodeFormat.h.

const (
	BarcodeFormatInvalid BarcodeFormat = 0xFFFF
	BarcodeFormatAll                  BarcodeFormat = 0x2A2A
	BarcodeFormatAllCreatable         BarcodeFormat = 0x772A
	BarcodeFormatAllGS1               BarcodeFormat = 0x472A
	BarcodeFormatAllIndustrial        BarcodeFormat = 0x492A
	BarcodeFormatAllLinear            BarcodeFormat = 0x6C2A
	BarcodeFormatAllMatrix            BarcodeFormat = 0x6D2A
	BarcodeFormatAllReadable          BarcodeFormat = 0x722A
	BarcodeFormatAllRetail            BarcodeFormat = 0x522A
	BarcodeFormatAztec                BarcodeFormat = 0x207A
	BarcodeFormatAztecCode            BarcodeFormat = 0x637A
	BarcodeFormatAztecRune            BarcodeFormat = 0x727A
	BarcodeFormatCodabar              BarcodeFormat = 0x2046
	BarcodeFormatCode128              BarcodeFormat = 0x2043
	BarcodeFormatCode32               BarcodeFormat = 0x3241
	BarcodeFormatCode39               BarcodeFormat = 0x2041
	BarcodeFormatCode39Ext            BarcodeFormat = 0x6541
	BarcodeFormatCode39Std            BarcodeFormat = 0x7341
	BarcodeFormatCode93               BarcodeFormat = 0x2047
	BarcodeFormatCompactPDF417        BarcodeFormat = 0x634C
	BarcodeFormatDXFilmEdge           BarcodeFormat = 0x7858
	BarcodeFormatDataBar              BarcodeFormat = 0x2065
	BarcodeFormatDataBarExp           BarcodeFormat = 0x6565
	BarcodeFormatDataBarExpStk        BarcodeFormat = 0x4565
	BarcodeFormatDataBarLtd           BarcodeFormat = 0x6C65
	BarcodeFormatDataBarOmni          BarcodeFormat = 0x6F65
	BarcodeFormatDataBarStk           BarcodeFormat = 0x7365
	BarcodeFormatDataBarStkOmni       BarcodeFormat = 0x4F65
	BarcodeFormatDataMatrix           BarcodeFormat = 0x2064
	BarcodeFormatEAN13                BarcodeFormat = 0x3145
	BarcodeFormatEAN2                 BarcodeFormat = 0x3245
	BarcodeFormatEAN5                 BarcodeFormat = 0x3545
	BarcodeFormatEAN8                 BarcodeFormat = 0x3845
	BarcodeFormatEANUPC               BarcodeFormat = 0x2045
	BarcodeFormatISBN                 BarcodeFormat = 0x6945
	BarcodeFormatITF                  BarcodeFormat = 0x2049
	BarcodeFormatITF14                BarcodeFormat = 0x3449
	BarcodeFormatMaxiCode             BarcodeFormat = 0x2055
	BarcodeFormatMicroPDF417          BarcodeFormat = 0x6D4C
	BarcodeFormatMicroQRCode          BarcodeFormat = 0x6D51
	BarcodeFormatOtherBarcode         BarcodeFormat = 0x2058
	BarcodeFormatPDF417               BarcodeFormat = 0x204C
	BarcodeFormatPZN                  BarcodeFormat = 0x7041
	BarcodeFormatQRCode               BarcodeFormat = 0x2051
	BarcodeFormatQRCodeModel1         BarcodeFormat = 0x3151
	BarcodeFormatQRCodeModel2         BarcodeFormat = 0x3251
	BarcodeFormatRMQRCode             BarcodeFormat = 0x7251
	BarcodeFormatUPCA                 BarcodeFormat = 0x6145
	BarcodeFormatUPCE                 BarcodeFormat = 0x6545
)
